import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigaton from "@/components/Navigation/Navigaton";
import { Suspense } from 'react';
import NetworkStatus from "./networkStatus";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense fallback={<p>Login..</p>}>
          <NetworkStatus/>
          <Navigaton />
          {children}
          <div id="modal-root"></div>
        </Suspense>
      </body>
    </html>
  );
}
