import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigaton from "@/components/Navigation/Navigaton";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigaton/>
        {children}
        <div id="modal-root"></div>
        </body>
    </html>
  );
}
