import type { Metadata } from "next";
import { Suspense } from 'react';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';
import { Inter } from "next/font/google";
import Navigaton from "@/components/Navigation/Navigaton";
import Footer from "@/components/Footer/footer";
import Login from "@/src/app/[locale]/Login"
import './globals.css' 

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Your Love",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={`${inter.className} min-h-screen flex flex-col`} >
        <NextIntlClientProvider messages={messages}>
          <Suspense fallback={<Login />}>
            <Navigaton />
            <div className="flex-grow">{children}</div>
            <div id="modal-root"></div>
            <Footer />
          </Suspense>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
